### ISSUE TITLE
How to detect hangup?

### ISSUE THREAD

**Issue by probonopd** [bsmulders/CX300Control#2]
How to detect the user wanting to quit the call? E.g., putting the handset on hook without having the speaker or headset on?

**Comment by bsmulders** [comment]
Unfortunately, there is no direct event triggered when you hang up the phone. You will need to interpret the events to figure out what is happening.

**Comment by probonopd** [comment]
OK, that's what I am doing now:

```
 if((previous_message[4] == 0x40) and (this_message[4] != 0x40)):
                        print("onHook")
```
